/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Person;
import Business.PersonDir;
import Business.User;
import Business.UserDir;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bengre
 */
public class AppAdminWrkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWrkSpcJPanel
     */
    private JPanel cardSeqJPanel;
    private PersonDir pd;
    private UserDir ud;    
    AppAdminWrkAreaJPanel(JPanel cardSeqJPanel, PersonDir pd, UserDir ud,String name) {
        initComponents();
        this.cardSeqJPanel=cardSeqJPanel;
        this.pd=pd;
        this.ud=ud;
        jTextFieldPersonName.setText(name);
        populateTable();
    }

       
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)jTablePersonList.getModel();
        dtm.setRowCount(0);
        for(Person p: pd.getListOfPerson()){
            Object row[] = new Object[3];
            row[0] = p;
            row[1]= p.getLastName();
            row[2] = p.getSsn();
            dtm.addRow(row);                   
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldPersonName = new javax.swing.JTextField();
        jButtonLogOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonAddUser = new javax.swing.JButton();
        jButtonGetUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUserList = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButtonAddPerson = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Application Admin Work Space");

        jTextFieldPersonName.setEditable(false);

        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        jTablePersonList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "SSN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePersonList);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Person List");

        jButtonAddUser.setText("Add Account");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        jButtonGetUser.setText("Get User Account  List");
        jButtonGetUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetUserActionPerformed(evt);
            }
        });

        jTableUserList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableUserList);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("User Account List");

        jButtonAddPerson.setText("Add Person");
        jButtonAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonLogOut)
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAddPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGetUser))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogOut))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGetUser)
                    .addComponent(jButtonAddUser)
                    .addComponent(jButtonAddPerson))
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPersonActionPerformed
        // TODO add your handling code here:
        AddPersonJPanelAppAdmin panel = new AddPersonJPanelAppAdmin(cardSeqJPanel,pd);
        cardSeqJPanel.add("AddPersonJPanelAppAdmin",panel);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);
    }//GEN-LAST:event_jButtonAddPersonActionPerformed

    private void jButtonGetUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetUserActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = jTablePersonList.getSelectedRow();
        
        if(selectedRowValue >= 0){
            Person p= (Person)jTablePersonList.getValueAt(selectedRowValue, 0);
            ArrayList<User> tempList = p.getUserList();
            DefaultTableModel dtm = (DefaultTableModel)jTableUserList.getModel();
            dtm.setRowCount(0);
            for(User u: tempList){
            Object row[] = new Object[3];
            row[0] = u;
            row[1]= u.getPassword();
            row[2] = u.getRole();
            dtm.addRow(row);                
    }
        }
        else
            JOptionPane.showMessageDialog(null,"Please select a record to view");
    }//GEN-LAST:event_jButtonGetUserActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
        LoginJPanel panel = new LoginJPanel(cardSeqJPanel,pd,ud);
        cardSeqJPanel.add("LoginJPanel",panel);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        // TODO add your handling code here:
        AddUserJPanelAppAdmin panel = new AddUserJPanelAppAdmin(cardSeqJPanel,pd,ud);
        cardSeqJPanel.add("AddUserJPanelAppAdmin",panel);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);
    }//GEN-LAST:event_jButtonAddUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPerson;
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonGetUser;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePersonList;
    private javax.swing.JTable jTableUserList;
    private javax.swing.JTextField jTextFieldPersonName;
    // End of variables declaration//GEN-END:variables
}
