/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Person;
import Business.PersonDir;
import Business.User;
import Business.UserDir;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bengre
 */
public class SystemAdminWrkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWrkAreaJPanel
     */
    private JPanel cardSeqJPanel;
    private PersonDir pd;
    private UserDir ud; 

    SystemAdminWrkAreaJPanel(JPanel cardSeqJPanel, PersonDir pd, UserDir ud, String name) {
        initComponents();
        this.cardSeqJPanel=cardSeqJPanel;
        this.pd=pd;
        this.ud=ud;
        jTextFieldPersonName.setText(name);
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)jTableUserList.getModel();
        dtm.setRowCount(0);
        HashMap<String,User> temphash = ud.getUserMap();
        for(String name: temphash.keySet()){
            User u= temphash.get(name);
            Object row[] = new Object[4];
            row[0] = u;
            row[1]= u.getPassword();
            row[2] = u.getRole();
            row[3] = u.getStatus();
            dtm.addRow(row);                   
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUserList = new javax.swing.JTable();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldUserName = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jButtonEditInfo = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldPersonName = new javax.swing.JTextField();
        jButtonLogOut = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage User Accounts");

        jTableUserList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Password", "Role", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUserList);
        if (jTableUserList.getColumnModel().getColumnCount() > 0) {
            jTableUserList.getColumnModel().getColumn(0).setResizable(false);
            jTableUserList.getColumnModel().getColumn(1).setResizable(false);
            jTableUserList.getColumnModel().getColumn(2).setResizable(false);
            jTableUserList.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonSearch.setText("Search Account");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonEditInfo.setText("Edit Info");
        jButtonEditInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditInfoActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add Account");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTextFieldPersonName.setEditable(false);

        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButtonLogOut))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAdd)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(219, 219, 219)
                                            .addComponent(jButtonEditInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jButtonSearch)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogOut))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSearch)
                        .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonEditInfo))
                .addGap(18, 18, 18)
                .addComponent(jButtonAdd)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
         LoginJPanel panel = new LoginJPanel(cardSeqJPanel,pd,ud);
        cardSeqJPanel.add("LoginJPanel",panel);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = jTableUserList.getSelectedRow();
        
        if(selectedRowValue >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to Delete this person and associated users", "Warning" , dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION){
                User u= (User)jTableUserList.getValueAt(selectedRowValue, 0);
                ud.removeUser(u.getName());
                JOptionPane.showMessageDialog(null,"Record Deleted");
                populateTable();
        }
            else
            JOptionPane.showMessageDialog(null,"Please select a record to delete");
        }
    
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldUserName.getText();
        if(name == null)
            JOptionPane.showMessageDialog(null,"Enter username!!!");
        else{
            User u = ud.getUserDetails(name);
            EditUserJPanel panel = new EditUserJPanel(cardSeqJPanel,u);
            cardSeqJPanel.add("EditUserJPanel",panel);
            CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
            layout.next(cardSeqJPanel);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonEditInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditInfoActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = jTableUserList.getSelectedRow();
        if(selectedRowValue >= 0){
            User u= (User)jTableUserList.getValueAt(selectedRowValue, 0);
            EditUserJPanel panel = new EditUserJPanel(cardSeqJPanel,u);
            cardSeqJPanel.add("EditUserJPanel",panel);
            CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
            layout.next(cardSeqJPanel);
        }
        else
            JOptionPane.showMessageDialog(null,"Please select a record to view");
    }//GEN-LAST:event_jButtonEditInfoActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        AddUserJPanel panel = new AddUserJPanel(cardSeqJPanel,pd,ud);
        cardSeqJPanel.add("AddUserJPanel",panel);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);
    }//GEN-LAST:event_jButtonAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEditInfo;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUserList;
    private javax.swing.JTextField jTextFieldPersonName;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
