/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SalesPerson;

import Business.Busines;
import Business.Busines;
import Business.CustomerDir;
import Business.MarketList;
import Business.MasterOrderList;
import Business.OrderItem;
import Business.Person;
import Business.PersonDir;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Minal
 */
public class SalesAgentWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SalesAgentWorkArea
     */
    public SalesAgentWorkArea() {
        initComponents();
    }
    private JPanel userProcessContainer;
    private Busines b;
    private Person p;
    private CustomerDir cd;
    private MarketList ml;
    private MasterOrderList mol;
    SalesAgentWorkArea(JPanel userProcessContainer, Busines b, Person p) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.b=b;
        this.p=p;
        jTextFieldName.setText(p.getFirstName() + " " + p.getLastName());
        cd = b.getCd();
        ml = b.getMl();
        mol = b.getMol();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddCustomer = new javax.swing.JButton();
        btnStartSalesOrder = new javax.swing.JButton();
        btnViewOrder = new javax.swing.JButton();
        btnViewPerformance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();

        btnAddCustomer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnStartSalesOrder.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnStartSalesOrder.setText("Start Sales Order");
        btnStartSalesOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSalesOrderActionPerformed(evt);
            }
        });

        btnViewOrder.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnViewOrder.setText("View Order");
        btnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderActionPerformed(evt);
            }
        });

        btnViewPerformance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnViewPerformance.setText("View Performance");
        btnViewPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPerformanceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sales Person Work Area");

        jTextFieldName.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnViewPerformance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStartSalesOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1)))
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnAddCustomer)
                .addGap(101, 101, 101)
                .addComponent(btnStartSalesOrder)
                .addGap(91, 91, 91)
                .addComponent(btnViewOrder)
                .addGap(106, 106, 106)
                .addComponent(btnViewPerformance)
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        AddCustomer panel = new AddCustomer(userProcessContainer,ml,cd);
        userProcessContainer.add("ManageProductCatalog", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnStartSalesOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSalesOrderActionPerformed
        // TODO add your handling code here:
        SelectMarketForOrder panel = new SelectMarketForOrder(userProcessContainer, b ,p);
        userProcessContainer.add("MarketOrder", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStartSalesOrderActionPerformed

    private void btnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderActionPerformed
        // TODO add your handling code here:
        ViewOrder panel = new ViewOrder(userProcessContainer, mol,p);
        userProcessContainer.add("ManageProductCatalog", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewOrderActionPerformed

    private void btnViewPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPerformanceActionPerformed
        // TODO add your handling code here:
        ViewPerformance panel = new ViewPerformance(userProcessContainer, p);
        userProcessContainer.add("ManageProductCatalog", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPerformanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnStartSalesOrder;
    private javax.swing.JButton btnViewOrder;
    private javax.swing.JButton btnViewPerformance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
