
package Interface.SalesPerson;

import Business.MasterOrderList;
import Business.Order;
import Business.OrderItem;
import Business.Person;
import Interface.SupplierWork.ManageProductCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class ViewOrder extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrder
     */
private JPanel userProcessContainer;
private MasterOrderList mol;
private Person p;
private List<Order> orderList = new ArrayList();
    ViewOrder(JPanel userProcessContainer, MasterOrderList mol, Person p) {
            initComponents();
            this.userProcessContainer=userProcessContainer;
            this.mol=mol;
            this.p = p;            
            orderList = getList();
            populateTable(orderList);
            }
    
    private List getList(){
        List<Order> listOfOrder = new ArrayList();
        for(Order ord: mol.getListOfOrders()){
            if(ord.getP().equals(p))
                listOfOrder.add(ord);
        }
        return listOfOrder;
    }
    
    private void populateTable(List<Order> listOfOrder){
        DefaultTableModel dtm = (DefaultTableModel)jTableOrderList.getModel();
        dtm.setRowCount(0);
        for(Order o:listOfOrder){
            double comission = o.expectedRevenue() * 0.1;
            Object row[] = new Object[7];
            row[0] = o;
            row[1]= o.getM().getName();
            row[2] = o.expectedRevenue();
            row[3] = o.totalRevenue();
            row[4] = comission;;
            row[5] = o.totalComission() - comission;
            row[6] = o.totalComission();
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrderList = new javax.swing.JTable();

        jButton3.setText("<<Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Order List");

        jTableOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Market", "Target Sales", "Invoice Total", "Comission", "Bonus", "Total Comission"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableOrderList);
        if (jTableOrderList.getColumnModel().getColumnCount() > 0) {
            jTableOrderList.getColumnModel().getColumn(0).setResizable(false);
            jTableOrderList.getColumnModel().getColumn(1).setResizable(false);
            jTableOrderList.getColumnModel().getColumn(2).setResizable(false);
            jTableOrderList.getColumnModel().getColumn(3).setResizable(false);
            jTableOrderList.getColumnModel().getColumn(4).setResizable(false);
            jTableOrderList.getColumnModel().getColumn(5).setResizable(false);
            jTableOrderList.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton3)
                .addContainerGap(770, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(308, 308, 308))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOrderList;
    // End of variables declaration//GEN-END:variables
}
