/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlineDirectory;
import Business.Airlines;
import Business.CustomerDir;
import Business.Flights;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bengre
 */
public class ResultFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResultFlightJPanel
     */
    private JPanel cardSeqJPanel; 
    private TravelAgency ta; 
    private List<Flights> tempList;
    private AirlineDirectory ad;
    private CustomerDir cd;
    
    ResultFlightJPanel(JPanel cardSeqJPanel, TravelAgency ta, List<Flights> tempList) {
        initComponents();
        this.cardSeqJPanel= cardSeqJPanel;
        this.ta = ta;
        this.tempList=tempList;
        this.ad=ta.getAd();
        this.cd=ta.getCd();
        populateTables();
        
    }
    
    public void populateTables(){
        DefaultTableModel dtm = (DefaultTableModel)jTableFlightResult.getModel();
        dtm.setRowCount(0);
        for(Flights f: tempList){
            Object row[] = new Object[5];
            row[0] = f;
            row[1]= f.getSrcAirport();
            row[2] = f.getDestAirport();
            row[3] = f.getDeptTime();
            dtm.addRow(row);                  
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFlightResult = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jButtonBook = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Available Flights");

        jTableFlightResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FlightId", "From", "To", "Dept Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFlightResult);
        if (jTableFlightResult.getColumnModel().getColumnCount() > 0) {
            jTableFlightResult.getColumnModel().getColumn(0).setResizable(false);
            jTableFlightResult.getColumnModel().getColumn(1).setResizable(false);
            jTableFlightResult.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonBack.setText("<Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonBook.setText("Book Seat");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 221, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBook)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(212, 212, 212))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBook)
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        cardSeqJPanel.remove(this);
        CardLayout layout = (CardLayout)cardSeqJPanel.getLayout();
        layout.previous(cardSeqJPanel);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = jTableFlightResult.getSelectedRow();
        
        if(selectedRowValue >= 0){
            Flights f= (Flights)jTableFlightResult.getValueAt(selectedRowValue, 0);
            BookSeatsJPanel panel = new BookSeatsJPanel(cardSeqJPanel,f,cd,ad);
            cardSeqJPanel.add("BookSeatsJPanel",panel);
            CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
            layout.next(cardSeqJPanel);
        }
        else
            JOptionPane.showMessageDialog(null,"Please select a flight to book seat"); 
    }//GEN-LAST:event_jButtonBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFlightResult;
    // End of variables declaration//GEN-END:variables
}
