/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Bengre
 */
public class TAAdminWrkSpaceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TAAdminWrkSpaceJPanel
     */
    private TravelAgency ta;
    private JPanel cardSeqJPanel;
    TAAdminWrkSpaceJPanel(JPanel cardSeqJPanel, TravelAgency ta) {
        initComponents();
        this.cardSeqJPanel=cardSeqJPanel;
        this.ta = ta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonViewCustDir = new javax.swing.JButton();
        jButtonViewALDir = new javax.swing.JButton();
        jButtonViewMasterSch = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Travel Agency Work Space");

        jButtonViewCustDir.setText("View Customer Directory");
        jButtonViewCustDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewCustDirActionPerformed(evt);
            }
        });

        jButtonViewALDir.setText("View Airline Directory");
        jButtonViewALDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewALDirActionPerformed(evt);
            }
        });

        jButtonViewMasterSch.setText("View Master Schedule");
        jButtonViewMasterSch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewMasterSchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewCustDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewALDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewMasterSch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(262, 262, 262))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jButtonViewCustDir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButtonViewALDir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonViewMasterSch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewCustDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewCustDirActionPerformed
        // TODO add your handling code here:
        CustomerDirJPanel panel = new CustomerDirJPanel(cardSeqJPanel, ta);
        cardSeqJPanel.add("CustomerDirJPanel",panel);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);
    }//GEN-LAST:event_jButtonViewCustDirActionPerformed

    private void jButtonViewALDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewALDirActionPerformed
        // TODO add your handling code here:
        AirlineDirectoryJPanel panel = new AirlineDirectoryJPanel(cardSeqJPanel, ta);
        cardSeqJPanel.add("AirlineDirectoryJPanel",panel);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);        
    }//GEN-LAST:event_jButtonViewALDirActionPerformed

    private void jButtonViewMasterSchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewMasterSchActionPerformed
        // TODO add your handling code here:
        MasterScheduleJPanel panel = new MasterScheduleJPanel(cardSeqJPanel, ta);
        cardSeqJPanel.add("MasterScheduleJPanel",panel);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel); 
    }//GEN-LAST:event_jButtonViewMasterSchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonViewALDir;
    private javax.swing.JButton jButtonViewCustDir;
    private javax.swing.JButton jButtonViewMasterSch;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
