/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlineDirectory;
import Business.Airlines;
import Business.Flights;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bengre
 */
public class TicketBookAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TicketBookAdminJPanel
     */
    private JPanel cardSeqJPanel;
    private TravelAgency ta;
    private AirlineDirectory ad;
    private List<Flights> tempList;
    TicketBookAdminJPanel(JPanel cardSeqJPanel, TravelAgency ta) {
        initComponents();
        this.cardSeqJPanel=cardSeqJPanel;
        this.ta=ta;
        this.ad = ta.getAd();
        this.tempList = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFlightId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFrom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldQuarter = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ticket Booking Work Space");

        jLabel2.setText("Flight Id");

        jLabel3.setText("From");

        jLabel4.setText("To");

        jLabel5.setText("Time of day");

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabel6.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addComponent(jTextFieldFlightId, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(71, 71, 71)
                        .addComponent(jTextFieldFrom))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSearch)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldQuarter)
                            .addComponent(jTextFieldTo)
                            .addComponent(jTextFieldDate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldFlightId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldQuarter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonSearch)
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String flightId=jTextFieldFlightId.getText();
        String from = jTextFieldFrom.getText();
        String to = jTextFieldTo.getText();
        String quarter = jTextFieldQuarter.getText();
        String date = jTextFieldDate.getText();
        
        
        if(flightId.isEmpty() && from.isEmpty() && to.isEmpty() && quarter.isEmpty() && date.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter values","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            for(Airlines a: ad.getListofAirlines()){
                for(Flights f : a.getSchedule()){
                   if(isFlightId(f, flightId) && isTo(f, to) && isFrom(f, from) && isQuarter(f, quarter) && isDate(f, date)){
                       tempList.add(f);
                   }
                }
                
            }                
             
        }
        
        ResultFlightJPanel panel = new ResultFlightJPanel(cardSeqJPanel,ta,tempList);
        cardSeqJPanel.add("ResultFlightJPanel",panel);
        CardLayout layout = (CardLayout) cardSeqJPanel.getLayout();
        layout.next(cardSeqJPanel);
        
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    
    private boolean isFlightId(Flights f, String flightId){
        if(flightId.isEmpty()){
            return true;
        }    
        else{
            if(f.getFlightId().equalsIgnoreCase(flightId))
                return true;
            else 
                return false;
        }      
    }
    
     private boolean isFrom(Flights f, String from){
        if(from.isEmpty())
            return true;
        else
            if(f.getSrcAirport().equalsIgnoreCase(from))
                return true;
            else 
                return false;
    }
     
      private boolean isTo(Flights f, String to){
        if(to.isEmpty())
            return true;
        else
            if(f.getDestAirport().equalsIgnoreCase(to))
                return true;
            else 
                return false;
    }
      
       private boolean isQuarter(Flights f, String quarter){
        if(quarter.isEmpty())
            return true;
        else
            if(f.getQuarter().equalsIgnoreCase(quarter))
                return true;
            else 
                return false;
    }
       
       private boolean isDate(Flights f, String date){
        if(date.isEmpty())
            return true;
        else
            if(convertDate(f.getDeptTime()) == convertDate(date))
                return true;
            else 
                return false;
    }
       
       private Date convertDate(String date){
           DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy"); 
        try {
            Date startDate = formatter.parse(date);
            return startDate;
        } catch (ParseException ex) {
            Logger.getLogger(TicketBookAdminJPanel.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldFlightId;
    private javax.swing.JTextField jTextFieldFrom;
    private javax.swing.JTextField jTextFieldQuarter;
    private javax.swing.JTextField jTextFieldTo;
    // End of variables declaration//GEN-END:variables
}
