/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;

import Business.Airliner;
import Business.Airplanes;
import Business.Manufacturer;
import Business.Schedule;
import java.awt.FlowLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.sql.Timestamp;
import java.util.Enumeration;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Bengre
 */
public class AddAPJPanel extends javax.swing.JPanel {

    /** Creates new form AddAPJPanel */
    private Airliner al;
    private String filePath;
    AddAPJPanel(Airliner al) {
        initComponents();
        this.al = al;
    }
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    public void refreshTextBoxes(){
        jTextFieldAirlinesName.setText("");
        jTextFieldCapacity.setText("");
        jTextFieldDept.setText("");
        jTextFieldDestAirport.setText("");
        jTextFieldExpiry.setText("");
        jTextFieldManuName.setText("");
        jTextFieldModel.setText("");
        jTextFieldSerialNo.setText("");
        jTextFieldSourceAirPort.setText("");
        jTextFieldYearManu.setText("");
    }
    
      
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAvail = new javax.swing.ButtonGroup();
        jLabelAddAPHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSerialNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldYearManu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldModel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCapacity = new javax.swing.JTextField();
        jLabelAddAPHeader1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonAvailTrue = new javax.swing.JRadioButton();
        jRadioButtonAvailFalse = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldManuName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAirlinesName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSourceAirPort = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDept = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldExpiry = new javax.swing.JTextField();
        jButtonConfirm = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDestAirport = new javax.swing.JTextField();
        jButtonSelectFile = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonUpload = new javax.swing.JButton();

        jLabelAddAPHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAddAPHeader.setText("Airplane Information");
        jLabelAddAPHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setText("Serial No.");

        jTextFieldSerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSerialNoActionPerformed(evt);
            }
        });

        jLabel1.setText("Year of Manufacture");

        jTextFieldYearManu.setText("YYYY");

        jLabel2.setText("Model");

        jLabel5.setText("Capacity");

        jLabelAddAPHeader1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAddAPHeader1.setText("Add Airplanes");
        jLabelAddAPHeader1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setText("Availability");

        buttonGroupAvail.add(jRadioButtonAvailTrue);
        jRadioButtonAvailTrue.setText("Yes");
        jRadioButtonAvailTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAvailTrueActionPerformed(evt);
            }
        });

        buttonGroupAvail.add(jRadioButtonAvailFalse);
        jRadioButtonAvailFalse.setText("No");

        jLabel3.setText("Manufacturer Name");

        jLabel8.setText("Airlines");

        jTextFieldAirlinesName.setEditable(false);
        jTextFieldAirlinesName.setText("Emirates");

        jLabel9.setText("Source Airport");

        jLabel10.setText("Departure Time");

        jTextFieldDept.setText("YYYY-MM-DD HH:MM:SS");

        jLabel11.setText("Maintenance Expriy");

        jTextFieldExpiry.setText("MM-DD-YYYY");

        jButtonConfirm.setText("Add Airplane");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jLabel12.setText("Destination Airport");

        jButtonSelectFile.setText("Select File");
        jButtonSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectFileActionPerformed(evt);
            }
        });

        jButtonUpload.setText("Upload Data");
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAddAPHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldYearManu, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addComponent(jTextFieldModel)
                        .addComponent(jTextFieldCapacity))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonAvailTrue)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonAvailFalse)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConfirm)
                        .addGap(167, 167, 167))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDept)
                                    .addComponent(jTextFieldExpiry)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldManuName)
                                    .addComponent(jTextFieldAirlinesName, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSourceAirPort)
                                    .addComponent(jTextFieldDestAirport))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonSelectFile)
                .addGap(18, 18, 18)
                .addComponent(jButtonUpload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(418, Short.MAX_VALUE)
                    .addComponent(jLabelAddAPHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(362, 362, 362)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSelectFile)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpload))
                .addGap(59, 59, 59)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAddAPHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldManuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldYearManu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldAirlinesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldSourceAirPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jTextFieldDestAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3))
                    .addComponent(jTextFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButtonAvailTrue)
                    .addComponent(jRadioButtonAvailFalse))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConfirm)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabelAddAPHeader1)
                    .addContainerGap(470, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSerialNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSerialNoActionPerformed

    private void jRadioButtonAvailTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAvailTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonAvailTrueActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        // TODO add your handling code here:
        
        try{
            String serialNo = jTextFieldSerialNo.getText();
            String manuYear = jTextFieldYearManu.getText();
            int noOfSeats = Integer.parseInt(jTextFieldCapacity.getText());
            String availability = getSelectedButtonText(buttonGroupAvail);
            String manuName = jTextFieldManuName.getText();
            String modelName = jTextFieldModel.getText();
            String srcAirport = jTextFieldSourceAirPort.getText();
            String destAirport = jTextFieldDestAirport.getText();
            String deptTime = jTextFieldDept.getText();
            String mainExp = jTextFieldExpiry.getText();
            Airplanes a = al.addAirplane();
            Manufacturer m = al.addManufacturer();
            a.addSchedule(serialNo, srcAirport, destAirport, deptTime);
            a.setAirliner();
            a.setAvailability(availability);
            a.setMainExpDate(mainExp);
            a.setManuName(manuName);
            a.setManuYear(manuYear);
            a.setModelName(modelName);
            a.setNoOfSeats(noOfSeats);
            a.setSerialNo(serialNo);            
            m.setManuName(manuName);
            al.setCatLstUpd(System.currentTimeMillis());
            JOptionPane.showMessageDialog(null, "Records Added");
            refreshTextBoxes();
            }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please check the values entered");
        }
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectFileActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.showOpenDialog(null);
        File file = filechooser.getSelectedFile();
        filePath = file.getAbsolutePath();
        jTextField1.setText(filePath);
    }//GEN-LAST:event_jButtonSelectFileActionPerformed

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        // TODO add your handling code here:
        Scanner scanner;
        try {
            scanner = new Scanner(new FileReader(filePath));
            scanner.nextLine();
             while(scanner.hasNextLine()){
            String line = scanner.nextLine();
            String[] splits = line.split(",");
            
            String serialNo = splits[0];
            String manuYear = splits[1];
            int noOfSeats = Integer.parseInt(splits[2]);
            String availability = splits[3];
            String manuName =splits[4];
            String modelName = splits[5];
            String srcAirport = splits[6];
            String destAirport = splits[7];
            String deptTime = splits[8];
            String mainExp = splits[9];
            Airplanes a = al.addAirplane();
            Manufacturer m = al.addManufacturer();
            a.setAirliner();
            a.setAvailability(availability);
            a.setMainExpDate(mainExp);
            a.setManuName(manuName);
            a.setManuYear(manuYear);
            a.setModelName(modelName);
            a.setNoOfSeats(noOfSeats);
            a.setSerialNo(serialNo);
            m.setManuName(manuName);
            a.addSchedule(serialNo, srcAirport, destAirport, deptTime);
            al.setCatLstUpd(System.currentTimeMillis());
            
            }
            } catch (FileNotFoundException ex) {
            Logger.getLogger(AddAPJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Records Uploaded");
            jTextField1.setText("");
       
    }//GEN-LAST:event_jButtonUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAvail;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonSelectFile;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAddAPHeader;
    private javax.swing.JLabel jLabelAddAPHeader1;
    private javax.swing.JRadioButton jRadioButtonAvailFalse;
    private javax.swing.JRadioButton jRadioButtonAvailTrue;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAirlinesName;
    private javax.swing.JTextField jTextFieldCapacity;
    private javax.swing.JTextField jTextFieldDept;
    private javax.swing.JTextField jTextFieldDestAirport;
    private javax.swing.JTextField jTextFieldExpiry;
    private javax.swing.JTextField jTextFieldManuName;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldSerialNo;
    private javax.swing.JTextField jTextFieldSourceAirPort;
    private javax.swing.JTextField jTextFieldYearManu;
    // End of variables declaration//GEN-END:variables

}
