/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SalesPerformance;

import Business.Busines;
import Business.Market;
import Business.MarketList;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siri chowdhary
 */
public class MarketRevenueJPanel extends javax.swing.JPanel {
     

    /**
     * Creates new form MarketRevenueJPanel
     */
    private JPanel userProcessContainer;
    private Busines b;
    public MarketRevenueJPanel(JPanel userProcessContainer, Busines b) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.b=b;
        populateTable();
    }
    
    public void populateTable(){
        MarketList ml = b.getMl();
        DefaultTableModel dtm = (DefaultTableModel)revenuebymarketTable.getModel();
        dtm.setRowCount(0);
        for(Market m:ml.getListOfMarket()){
            Object row[] = new Object[7];
            row[0] = m;
            row[1] = m.getAboveTarget();
            row[2] = m.getOnTarget();
            row[3] = m.getBelowTarget();
            row[4] = m.getTagertSales();
            row[5] = m.getTotRevenue();
            row[6] = m.getTotRevenue() - m.getTagertSales();
            dtm.addRow(row);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        revenuebymarketTable = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        revenuebymarketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Market Name", "Above Target", "On Target", "Below Target", "Expected Revenue", "Revenue", "Gap"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(revenuebymarketTable);
        if (revenuebymarketTable.getColumnModel().getColumnCount() > 0) {
            revenuebymarketTable.getColumnModel().getColumn(0).setResizable(false);
            revenuebymarketTable.getColumnModel().getColumn(1).setResizable(false);
            revenuebymarketTable.getColumnModel().getColumn(2).setResizable(false);
            revenuebymarketTable.getColumnModel().getColumn(3).setResizable(false);
            revenuebymarketTable.getColumnModel().getColumn(4).setResizable(false);
            revenuebymarketTable.getColumnModel().getColumn(5).setResizable(false);
            revenuebymarketTable.getColumnModel().getColumn(6).setResizable(false);
        }

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Market Analysis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(backbtn)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable revenuebymarketTable;
    // End of variables declaration//GEN-END:variables
}
