/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SalesPerformance;

import Business.Busines;
import Business.Market;
import Business.MasterOrderList;
import Business.Order;
import Business.Person;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siri chowdhary
 */
public class PersonListbyRevenueJPanel extends javax.swing.JPanel {
   

    /**
     * Creates new form PersonListbyRevenueJPanel
     */
    private JPanel userProcessContainer;
    private Busines b;
    private Market m;
    private MasterOrderList mol;
    ArrayList<Order> tempList;
    java.util.List<Person> personList = new ArrayList();
    PersonListbyRevenueJPanel(JPanel userProcessContainer, Busines b, Market m) {
        initComponents();
        tempList = new ArrayList();
        this.userProcessContainer = userProcessContainer;
        this.b=b;
        this.m = m;
        mol = b.getMol();
        personList = getList();
        populateTable(personList);
    }
    
    private List getList(){
        List<Person> listOfPerson = new ArrayList();
        for(Order o: mol.getListOfOrders()){
            if(m == o.getM())
                tempList.add(o);
        }
        for(Order o: tempList){
            listOfPerson.add(o.getP());
        }
        listOfPerson = listOfPerson.stream().distinct().collect(Collectors.toList());
        listOfPerson.sort(Comparator.comparing(Person::getTotRevenue).reversed());
        return listOfPerson;
    }
    
    private void populateTable(List<Person> listOfPerson){
        DefaultTableModel dtm = (DefaultTableModel)personlistbyrevenueTable.getModel();
        dtm.setRowCount(0);
        for(Person p: listOfPerson){
            Object row[] = new Object[7];
            row[0] = p.getFirstName() + " " + p.getLastName();
            row[1] = p.getAboveTarget();
            row[2] = p.getBelowTarget();
            row[3] = p.getOnTarget();
            row[4] = p.getTotRevenue();
            row[5] = p.getTargetPrice();
            row[6] = p.getTotRevenue() - p.getTargetPrice();
            dtm.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        personlistbyrevenueTable = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        personlistbyrevenueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Sold Above Target", "Sold Below Target", "Sold On Target", "Total Revenue Generated", "Expected Revenue", "Gap"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(personlistbyrevenueTable);
        if (personlistbyrevenueTable.getColumnModel().getColumnCount() > 0) {
            personlistbyrevenueTable.getColumnModel().getColumn(0).setResizable(false);
            personlistbyrevenueTable.getColumnModel().getColumn(1).setResizable(false);
            personlistbyrevenueTable.getColumnModel().getColumn(2).setResizable(false);
            personlistbyrevenueTable.getColumnModel().getColumn(3).setResizable(false);
            personlistbyrevenueTable.getColumnModel().getColumn(4).setResizable(false);
            personlistbyrevenueTable.getColumnModel().getColumn(5).setResizable(false);
            personlistbyrevenueTable.getColumnModel().getColumn(6).setResizable(false);
        }

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel1.setText("PERSON LIST BY REVENUE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backbtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(backbtn)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable personlistbyrevenueTable;
    // End of variables declaration//GEN-END:variables
}
