/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SalesPerformance;

import Business.Busines;
import Business.MasterOrderList;
import Business.Order;
import Business.Person;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siri chowdhary
 */
public class SalesAgentPerformanceJPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form SalesAgentPerformanceJPanel
     */
    private JPanel userProcessContainer;
    private Busines b;
    private MasterOrderList mol;
    java.util.List<Person> personList = new ArrayList();
    public SalesAgentPerformanceJPanel(JPanel userProcessContainer, Busines b) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.b = b;
        mol= b.getMol();
        personList = getList();
        populateTable(personList);
    }
    
    private List getList(){
        List<Person> listOfPerson = new ArrayList();
        for(Order o: mol.getListOfOrders()){
            listOfPerson.add(o.getP());
        }
        listOfPerson = listOfPerson.stream().distinct().collect(Collectors.toList());
        listOfPerson.sort(Comparator.comparing(Person::getAboveTarget).reversed());
        return listOfPerson;
    }
    
    private void populateTable(List<Person> listOfPerson){
        DefaultTableModel dtm = (DefaultTableModel)salesagentperformanceTable.getModel();
        dtm.setRowCount(0);
        for(Person p: listOfPerson){
            Object row[] = new Object[7];
            row[0] = p.getFirstName() + " " + p.getLastName();
            row[1] = p.getAboveTarget();
            row[2] = p.getBelowTarget();
            row[3] = p.getOnTarget();
            row[4] = p.getTotRevenue();
            row[5] = p.getTargetPrice();
            row[6] = p.getTotRevenue() - p.getTargetPrice();
            dtm.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        salesagentperformanceTable = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        salesagentperformanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Above Target Price", "Below Target Price", "On Target Price", "Total Revenue", "Expected Revenue", "Gap"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(salesagentperformanceTable);
        if (salesagentperformanceTable.getColumnModel().getColumnCount() > 0) {
            salesagentperformanceTable.getColumnModel().getColumn(0).setResizable(false);
            salesagentperformanceTable.getColumnModel().getColumn(1).setResizable(false);
            salesagentperformanceTable.getColumnModel().getColumn(2).setResizable(false);
            salesagentperformanceTable.getColumnModel().getColumn(3).setResizable(false);
            salesagentperformanceTable.getColumnModel().getColumn(4).setResizable(false);
            salesagentperformanceTable.getColumnModel().getColumn(5).setResizable(false);
            salesagentperformanceTable.getColumnModel().getColumn(6).setResizable(false);
        }

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SALES AGENT PERFORMNACE BY  TARGET SALES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(backbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable salesagentperformanceTable;
    // End of variables declaration//GEN-END:variables
}
