/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SalesPerformance;

import Business.Busines;
import Business.Order;
import Business.Person;
import Business.Product;
import Business.ProductCatalog;
import Business.Supplier;
import Business.SupplierDir;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author siri chowdhary
 */
public class TopSoldProductsJPanel extends javax.swing.JPanel {
   

    /**
     * Creates new form TopSoldProductsJPanel
     */
    private JPanel userProcessContainer;
    private Busines b;
    private SupplierDir sd;
    java.util.List<Product> productList = new ArrayList();
    public TopSoldProductsJPanel(JPanel userProcessContainer, Busines b) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.b=b;
        sd = b.getSd();
        productList = getList();
        populateTable(productList);
    }
    
    private List getList(){
        List<Product> listOfProducts = new ArrayList();
        for(Supplier s:sd.getListOfSuppliers()){
                ProductCatalog prodCat = s.getPc();
                for(Product prod: prodCat.getListofProducts()){
                   listOfProducts.add(prod);
                }
            }
        listOfProducts = listOfProducts.stream().distinct().collect(Collectors.toList());
        listOfProducts.sort(Comparator.comparing(Product::getAboveTarget).reversed());
        return listOfProducts;
    }
    
    private void populateTable(List<Product> listOfProducts){
        DefaultTableModel dtm = (DefaultTableModel)topsoldproductsTable.getModel();
        dtm.setRowCount(0);
        for(Product p: listOfProducts){
            Object row[] = new Object[7];
            row[0] = p.getName();
            row[1] = p.getAboveTarget();
            row[2] = p.getBelowTarget();
            row[3] = p.getOnTarget();
            row[4] = p.getTotRevenue();
            row[5] = p.getTargetPrice();
            row[6] = p.getTotRevenue() - p.getTargetPrice();
            dtm.addRow(row);
        }        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        topsoldproductsTable = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        topsoldproductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Sold Above Target Price", "Sold Below Target Price", "Sold For Target Price", "Revenue Generated", "Expected Revenue", "Gap"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(topsoldproductsTable);
        if (topsoldproductsTable.getColumnModel().getColumnCount() > 0) {
            topsoldproductsTable.getColumnModel().getColumn(0).setResizable(false);
            topsoldproductsTable.getColumnModel().getColumn(1).setResizable(false);
            topsoldproductsTable.getColumnModel().getColumn(2).setResizable(false);
            topsoldproductsTable.getColumnModel().getColumn(3).setResizable(false);
            topsoldproductsTable.getColumnModel().getColumn(4).setResizable(false);
            topsoldproductsTable.getColumnModel().getColumn(5).setResizable(false);
            topsoldproductsTable.getColumnModel().getColumn(6).setResizable(false);
        }

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel1.setText("TOP SELLING PRODUCTS DEPENDING ON TARGET PRICE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(backbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable topsoldproductsTable;
    // End of variables declaration//GEN-END:variables
}
