/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageXeroxAdmin;

import Business.Person;
import Business.User;
import Business.UserDir;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author siri chowdhary
 */
public class CreateSalesAgentJPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form CreateSalesAgentJPanel
     */
    private JPanel userProcessContainer;
    private Person p;
    private UserDir ud;

    CreateSalesAgentJPanel(JPanel userProcessContainer, Person p, UserDir ud) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ud=ud;
        this.p = p;        
    }
    
    public void refreshTextBoxes(){
        jTextFieldUserName.setText("");
        jTextFieldPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        createbtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create New Sales Agent");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 66, -1, -1));

        jLabel2.setText("UserName");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 162, -1, -1));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 230, -1, -1));
        add(jTextFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 159, 119, -1));
        add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 227, 119, -1));

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 394, -1, -1));

        createbtn.setText("Create");
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });
        add(createbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 325, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePersonJPanel managePersonJPanel = (ManagePersonJPanel) component;
        managePersonJPanel.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        // TODO add your handling code here:
        String name=jTextFieldUserName.getText();
        String password = jTextFieldPassword.getText();
        if("".equals(name) || "".equals(password) )
            JOptionPane.showMessageDialog(null,"Enter all values","Error", JOptionPane.ERROR_MESSAGE);
        else{
            User u = ud.addUser(name);
            u.setP(p);
            u.setPassword(password);
            u.setUserName(name);
            JOptionPane.showMessageDialog(null, "Login Details added successfully added");
            refreshTextBoxes();
        }
    }//GEN-LAST:event_createbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton createbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
