/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.BillDenominations;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.calendar.CalendarUtils;

/**
 *
 * @author Bengre
 */
public class CshWdJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CshWdJPanel
     */
    BillDenominations bd;
    private int accountBal;
    public CshWdJPanel() {
        initComponents();
        bd = new BillDenominations();
        accountBal = 2000;
        }
    
    public void verifyAmount(int amountEntered){
        if((amountEntered%5) != 0){
            JOptionPane.showMessageDialog(null, "Please enter a value which is a multiple of 5");
        }else if (amountEntered > accountBal)
            JOptionPane.showMessageDialog(null, "Please enter a value less that your current account balance. Your current Account balance is "+ accountBal);
        else {
        populateTable(amountEntered);
        accountBal= accountBal- amountEntered;
        JOptionPane.showMessageDialog(null, "Please collect your cash. Your current Account balance is "+ accountBal);
        }  
        }

    private void populateTable(int amountEntered) {
        DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        int i = 20;
        Object row[] = new Object[2];
        while(i>=5){     
            row[0] = "$" +i;
            if(i==20)
                row[1]= bd.getTwentyBill(amountEntered);
            else if (i==10)
                row[1]= bd.getTenBill(amountEntered);
            else
                row[1]= bd.getFiveBill(amountEntered);
            dtm.addRow(row);
            i=i/2;
            }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonFiveDol = new javax.swing.JButton();
        jButtonTenDol = new javax.swing.JButton();
        jButtonTwentyDol = new javax.swing.JButton();
        jButtonFiftyDol = new javax.swing.JButton();
        jButtonTwoHndDol = new javax.swing.JButton();
        jButtonHundDol = new javax.swing.JButton();
        jButtonOneFiveDol = new javax.swing.JButton();
        jButtonFiveHndDol = new javax.swing.JButton();
        jButtonThousDol = new javax.swing.JButton();
        jButtonGo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldOtherAmt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quick Cash");

        jButtonFiveDol.setText("$5");
        jButtonFiveDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiveDolActionPerformed(evt);
            }
        });

        jButtonTenDol.setText("$10");
        jButtonTenDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTenDolActionPerformed(evt);
            }
        });

        jButtonTwentyDol.setText("$20");
        jButtonTwentyDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwentyDolActionPerformed(evt);
            }
        });

        jButtonFiftyDol.setText("$50");
        jButtonFiftyDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiftyDolActionPerformed(evt);
            }
        });

        jButtonTwoHndDol.setText("$200");
        jButtonTwoHndDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwoHndDolActionPerformed(evt);
            }
        });

        jButtonHundDol.setText("$100");
        jButtonHundDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHundDolActionPerformed(evt);
            }
        });

        jButtonOneFiveDol.setText("$150");
        jButtonOneFiveDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneFiveDolActionPerformed(evt);
            }
        });

        jButtonFiveHndDol.setText("$500");
        jButtonFiveHndDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiveHndDolActionPerformed(evt);
            }
        });

        jButtonThousDol.setText("$1000");
        jButtonThousDol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThousDolActionPerformed(evt);
            }
        });

        jButtonGo.setText("Confirm");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        jLabel2.setText("Any Other Amount");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Cash Dispenser");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonFiveDol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTenDol, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(jButtonTwentyDol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonHundDol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jButtonFiftyDol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonOneFiveDol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldOtherAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonTwoHndDol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFiveHndDol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonThousDol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGo, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFiveDol)
                    .addComponent(jButtonFiftyDol)
                    .addComponent(jButtonTwoHndDol))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTenDol)
                    .addComponent(jButtonFiveHndDol)
                    .addComponent(jButtonHundDol))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTwentyDol)
                    .addComponent(jButtonThousDol)
                    .addComponent(jButtonOneFiveDol))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGo)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldOtherAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        // TODO add your handling code here:
        try{        
        int amountEntered = Integer.parseInt(jTextFieldOtherAmt.getText());
        verifyAmount(amountEntered);
        }       
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter numerical value");
        }
    }//GEN-LAST:event_jButtonGoActionPerformed

    private void jButtonFiveDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiveDolActionPerformed
        // TODO add your handling code here:
        int amountEntered = 5;
        verifyAmount(amountEntered);
    }//GEN-LAST:event_jButtonFiveDolActionPerformed

    private void jButtonTenDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTenDolActionPerformed
        // TODO add your handling code here:
        int amountEntered = 10;
        verifyAmount(amountEntered);
    }//GEN-LAST:event_jButtonTenDolActionPerformed

    private void jButtonTwentyDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwentyDolActionPerformed
        // TODO add your handling code here:
        int amountEntered = 20;
        verifyAmount(amountEntered);
    }//GEN-LAST:event_jButtonTwentyDolActionPerformed

    private void jButtonFiftyDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiftyDolActionPerformed
        // TODO add your handling code here:
        int amountEntered = 50;
        verifyAmount(amountEntered);
    }//GEN-LAST:event_jButtonFiftyDolActionPerformed

    private void jButtonHundDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHundDolActionPerformed
        // TODO add your handling code here:
        int amountEntered = 100;
        verifyAmount(amountEntered);
    }//GEN-LAST:event_jButtonHundDolActionPerformed

    private void jButtonOneFiveDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneFiveDolActionPerformed
        // TODO add your handling code here:
        int amountEntered = 150;
        verifyAmount(amountEntered);
    }//GEN-LAST:event_jButtonOneFiveDolActionPerformed

    private void jButtonTwoHndDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwoHndDolActionPerformed
        // TODO add your handling code here:
        int amountEntered = 200;
        verifyAmount(amountEntered);
    }//GEN-LAST:event_jButtonTwoHndDolActionPerformed

    private void jButtonFiveHndDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiveHndDolActionPerformed
        // TODO add your handling code here:
        int amountEntered = 500;
        verifyAmount(amountEntered);
    }//GEN-LAST:event_jButtonFiveHndDolActionPerformed

    private void jButtonThousDolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThousDolActionPerformed
        // TODO add your handling code here:
        int amountEntered = 1000;
        verifyAmount(amountEntered);
    }//GEN-LAST:event_jButtonThousDolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiftyDol;
    private javax.swing.JButton jButtonFiveDol;
    private javax.swing.JButton jButtonFiveHndDol;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JButton jButtonHundDol;
    private javax.swing.JButton jButtonOneFiveDol;
    private javax.swing.JButton jButtonTenDol;
    private javax.swing.JButton jButtonThousDol;
    private javax.swing.JButton jButtonTwentyDol;
    private javax.swing.JButton jButtonTwoHndDol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldOtherAmt;
    // End of variables declaration//GEN-END:variables
}
