/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Account;
import Business.AccountDir;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bengre
 */
public class ManageAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccountJPanel
     */
    private JPanel userProcessContainer;
    private AccountDir ad;    
    ManageAccountJPanel(JPanel userProcessContainer, AccountDir ad) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ad = ad;
        populateTables();
    }
    
    private void populateTables(){
        DefaultTableModel dtm = (DefaultTableModel)jTableAccntLst.getModel();
        dtm.setRowCount(0);
        
        for(Account a : ad.getAccountList()){
            Object row[] = new Object[4];
            row[0] = a;
            row[1]= a.getAccountNo();
            row[2]= a.getBankName();
            row[3]= a.getBalance();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAccntLst = new javax.swing.JTable();
        jButtonViewDetails = new javax.swing.JButton();
        jTextFieldAccountNumber = new javax.swing.JTextField();
        jButtonSearchAccNo1 = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        jTableAccntLst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Routing Number", "Account Number", "Bank Name", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAccntLst);
        if (jTableAccntLst.getColumnModel().getColumnCount() > 0) {
            jTableAccntLst.getColumnModel().getColumn(0).setResizable(false);
            jTableAccntLst.getColumnModel().getColumn(1).setResizable(false);
            jTableAccntLst.getColumnModel().getColumn(2).setResizable(false);
            jTableAccntLst.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonViewDetails.setText("View Details >");
        jButtonViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewDetailsActionPerformed(evt);
            }
        });

        jButtonSearchAccNo1.setText("Search by Account Number");
        jButtonSearchAccNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchAccNo1ActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete Account");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonBack.setText("<Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSearchAccNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jTextFieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(257, 257, 257)
                                .addComponent(jButtonViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchAccNo1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonViewDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = jTableAccntLst.getSelectedRow();
        
        if(selectedRowValue >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to Delete the Account Details", "Warning" , dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION){
            Account a= (Account)jTableAccntLst.getValueAt(selectedRowValue, 0);
            ad.deleteAccount(a);
            JOptionPane.showMessageDialog(null,"Record Deleted");
            populateTables();
        }
        else
            JOptionPane.showMessageDialog(null,"Please select a record to delete");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = jTableAccntLst.getSelectedRow();
        
        if(selectedRowValue >= 0){
            Account a= (Account)jTableAccntLst.getValueAt(selectedRowValue, 0);
            AccountDetailsJPanel panel = new AccountDetailsJPanel(userProcessContainer,a);
            userProcessContainer.add("AccountDetailsJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
            JOptionPane.showMessageDialog(null,"Please select a record to view");
    }//GEN-LAST:event_jButtonViewDetailsActionPerformed

    private void jButtonSearchAccNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchAccNo1ActionPerformed
        // TODO add your handling code here:
        Account result = ad.searchAccount(jTextFieldAccountNumber.getText());
        if(result == null)
            JOptionPane.showMessageDialog(null,"No result found","Information", JOptionPane.INFORMATION_MESSAGE);
        else{
            AccountDetailsJPanel panel = new AccountDetailsJPanel(userProcessContainer,result);
            userProcessContainer.add("AccountDetailsJPanel",panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            }
            
    }//GEN-LAST:event_jButtonSearchAccNo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearchAccNo1;
    private javax.swing.JButton jButtonViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAccntLst;
    private javax.swing.JTextField jTextFieldAccountNumber;
    // End of variables declaration//GEN-END:variables
}
