/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageMarketOffer;

import Business.Market;
import Business.MarketOffer;
import Business.MarketOfferCatalog;
import Business.Person;
import Business.Product;
import Interface.ManageXeroxAdmin.UpdatePersonJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bengre
 */
public class MarketOfferAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MarketOfferAdminJPanel
     */
    private JPanel userProcessContainer;
    private MarketOfferCatalog moc;
    public MarketOfferAdminJPanel(JPanel userProcessContainer, MarketOfferCatalog moc) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.moc = moc;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)jTableMarketOffer.getModel();
        dtm.setRowCount(0);
        for(MarketOffer mo: moc.getListOfMarketOffer()){
            Object row[] = new Object[5];
            Market m = mo.getM();
            Product p = mo.getP();
            row[0] = mo;
            row[1] = m.getName();
            row[2] = mo.getTarget();
            row[3] = mo.getFloor();
            row[4] = mo.getCeiling();
            dtm.addRow(row);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMarketOffer = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Market Offer Admin Work Area");

        jTableMarketOffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Market", "Target", "Floor", "Ceiling"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMarketOffer);
        if (jTableMarketOffer.getColumnModel().getColumnCount() > 0) {
            jTableMarketOffer.getColumnModel().getColumn(0).setResizable(false);
            jTableMarketOffer.getColumnModel().getColumn(1).setResizable(false);
            jTableMarketOffer.getColumnModel().getColumn(2).setResizable(false);
            jTableMarketOffer.getColumnModel().getColumn(3).setResizable(false);
            jTableMarketOffer.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Edit Market Offer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowValue = jTableMarketOffer.getSelectedRow();
        if(selectedRowValue >= 0){
        MarketOffer mo= (MarketOffer)jTableMarketOffer.getValueAt(selectedRowValue, 0);
        UpdateMarketOfferJPanel panel = new UpdateMarketOfferJPanel(userProcessContainer,mo);
        userProcessContainer.add("UpdateMarketOfferJPanel",panel);
        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
         else
            JOptionPane.showMessageDialog(null,"Please select a record to view");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMarketOffer;
    // End of variables declaration//GEN-END:variables
}
